#pragma once

// TODO ASSIGN ALL THE ANIMATION PATHS FOR EACH TYPE OF NPC

// TODO POTENTIALLY SAVE THE LOADED ANIMATIONS IN A SINGLE CLASS (IF UNREAL ALLOWS MULTIPLE OBJECT TO ACCESS THE SAME
// LOADED ANIMATION AT THE SAME TIME)